### ISSUE TITLE
 too many values to unpack (expected 2), line 210, in authenticate_user   username, password = auth_data.split(':')

### ISSUE THREAD

**Issue by yoosofan** [gvalkov/tornado-http-auth#1]
When a user put : (colon) on user name or password this packages produces this error.
 too many values to unpack (expected 2), line 210, in authenticate_user   username, password = auth_data.split(':')
It can be fixed simply by checking the number of colons if colon is prohibited in user name and password.

**Comment by gvalkov** [comment]
Fixed in 589a26405225a13c8f9d68e9132caeda38765150. Thanks.
